Repository GameDevWS2024/Corebound, pull requests merged in 2025-01, with the labels that each got.

#55 Removing the player
  assets/prompts/ally_system_prompt.txt
  assets/prompts/introduction_ally_system_prompt.txt
  scenes/levels/ExampleScene.tscn
  scenes/prefabs/Ally.tscn
  scenes/prefabs/Ally2.tscn
  scripts/AI/GeminiService.cs
  scripts/Ally.cs
  scripts/Chat.cs
  scripts/CombatAlly.cs
  scripts/Items/Inventory.cs
  scripts/Map.cs
  scripts/MouseControl.cs
  scripts/PathFindingMovement.cs
  scripts/Player.cs
Labels: [CODING]

#59 added Inventory GUI for allies
  Game.csproj
  assets/inventory/inventory-background.png
  assets/inventory/inventory-background.png.import
  assets/inventory/inventory-slot.png
  assets/inventory/inventory-slot.png.import
  assets/items/copper.png
  assets/items/copper.png.import
  assets/items/diamond.png
  assets/items/diamond.png.import
  assets/items/flashlight.png
  assets/items/flashlight.png.import
  assets/items/gold.png
  assets/items/gold.png.import
  assets/items/iron.png
  assets/items/iron.png.import
  assets/items/notebook.png
  assets/items/notebook.png.import
  assets/items/stone.png
  assets/items/stone.png.import
  assets/items/wood.png
  assets/items/wood.png.import
  project.godot
  scenes/prefabs/Ally.tscn
  scenes/prefabs/InventoryUiSlot.tscn
  scenes/prefabs/inventory_ui.tscn
  scripts/Ally.cs
  scripts/Interaction/ItemAdder.cs
  scripts/Items/Inventory.cs
  scripts/Items/InventoryUi.cs
  scripts/Items/InventoryUiSlot.cs
  scripts/Items/Itemstack.cs
  scripts/Items/Material.cs
Labels: enhancement, [CODING], Spielverlauf

#66 Skip IntroScene
  IntroScene.cs
Labels: enhancement, [DESIGN], [CODING]

#68 Level design and AI improvements final
  assets/items/lighted_torch.png
  assets/items/lighted_torch.png.import
  assets/items/torch.png
  assets/items/torch.png.import
  assets/prompts/ally2_prompt.txt
  assets/prompts/ally_system_prompt.txt
  assets/sprites/WorkerAllyIdleAn.png.import
  key.png
  key.png.import
  scenes/levels/ExampleScene.tscn
  scenes/levels/HauntedForest/insideBigHouse.tscn
  scenes/prefabs/ai_node.tscn
  scripts/AI/AiNode.cs
  scripts/AI/GeminiService.cs
  scripts/AI/VisibleForAI.cs
  scripts/Ally.cs
  scripts/Chat.cs
  scripts/Interaction/ItemAdder.cs
  scripts/Interaction/Removeable.cs
  scripts/Interaction/ShowWhileInRadius.cs
  scripts/Items/Inventory.cs
  scripts/Items/InventoryUi.cs
  scripts/Items/InventoryUiSlot.cs
  scripts/Items/Material.cs
  scripts/Items/Torch.cs
  scripts/MouseControl.cs
Labels: [CODING]

#74 Queues for Ally and GeminiService + added semaphore, SendSystemMessage function in Chat
  scenes/levels/ExampleScene.tscn
  scenes/levels/HauntedForest/insideBigHouse.tscn
  scenes/prefabs/Ally.tscn
  scripts/AI/AiNode.cs
  scripts/AI/GeminiService.cs
  scripts/AI/VisibleForAI.cs
  scripts/Ally.cs
  scripts/Chat.cs
  scripts/Interaction/Interactable.cs
  scripts/Interaction/Removeable.cs
  scripts/Interaction/ShowWhileInRadius.cs
  scripts/Items/Inventory.cs
  scripts/Map.cs
  scripts/PathFindingMovement.cs
Labels: bug, enhancement, [CODING]
